### ISSUE TITLE
HttpError: Not Found

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#51]
https://circleci.com/gh/prisma/prisma-label-sync/193 failed:

```
#!/bin/bash -eo pipefail
yarn sync
yarn run v1.17.3
$ ts-node src/index.ts
HttpError: Not Found
    at /home/circleci/project/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at Job.doExecute (/home/circleci/project/node_modules/bottleneck/light.js:405:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

The connected dry run had been successful: https://circleci.com/gh/prisma/prisma-label-sync/192

This run contained quite a lot of changes, so maybe this hit a API problem or limit.

From looking at the repos, most of the changes were applied correctly, but `prisma/prisma-engine` did not get changed (neither did it remove the old labels, nor did it add the new ones).

**Comment by janpio** [comment]
Cleanup commit that should have fixed the missing changes to `prisma-engine` also failed:
Successful dryrun: https://circleci.com/gh/prisma/prisma-label-sync/197
Failed actual run: https://circleci.com/gh/prisma/prisma-label-sync/198

As this is a new repo, could perhaps the user applying those changes (@timsuchanek) not have access to it? Will investigate.

**Comment by janpio** [comment]
We replaced the `GITHUB_TOKEN` of @timsuchanek with one of a new bot user (@prisma-label-sync-bot, token has `repo` scope) and the error persists, so that was not the problem.

The first commit that failed with this error message: https://github.com/prisma/prisma-label-sync/commit/4b874d0bf1fe1561392232d91a6b8ed7abb5efad I don't see anything wrong with it.

This could be something completely different, but the error message doesn't give any pointers. How can we proceed here @maticzav?

**Comment by janpio** [comment]
Yay, error went away over the weekend. @matthewmueller tested for me locally, and it just worked - now it also works here (tested via dependency bump PR). Doesn't make too much sense, as the token in Circle is still the same, but 🤷‍♀ 

(Github changed the "Triage" rights over the weekend, maybe this fixed things here. Also on Friday maybe Dom changed some of the rights of the bot whose token we are using from "Triage" to "Write" - and although this should not make a difference for creating and setting labels this could still be the cause.)
